# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo/echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="echo/echo.proto",
    package="echo",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0f\x65\x63ho/echo.proto\x12\x04\x65\x63ho"\x1a\n\x0b\x45\x63hoMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t26\n\x04\x45\x63ho\x12.\n\x04\x45\x63ho\x12\x11.echo.EchoMessage\x1a\x11.echo.EchoMessage"\x00\x62\x06proto3',
)


_ECHOMESSAGE = _descriptor.Descriptor(
    name="EchoMessage",
    full_name="echo.EchoMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="msg",
            full_name="echo.EchoMessage.msg",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=51,
)

DESCRIPTOR.message_types_by_name["EchoMessage"] = _ECHOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoMessage = _reflection.GeneratedProtocolMessageType(
    "EchoMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _ECHOMESSAGE,
        "__module__": "echo.echo_pb2"
        # @@protoc_insertion_point(class_scope:echo.EchoMessage)
    },
)
_sym_db.RegisterMessage(EchoMessage)


_ECHO = _descriptor.ServiceDescriptor(
    name="Echo",
    full_name="echo.Echo",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=53,
    serialized_end=107,
    methods=[
        _descriptor.MethodDescriptor(
            name="Echo",
            full_name="echo.Echo.Echo",
            index=0,
            containing_service=None,
            input_type=_ECHOMESSAGE,
            output_type=_ECHOMESSAGE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name["Echo"] = _ECHO

# @@protoc_insertion_point(module_scope)
